//! Data structures for the MarketplaceEscrowV1 contract

use soroban_sdk::{contracttype, Address, String};

/// Trade state constants
pub const ORDERED: u32 = 0;
pub const FULFILLED: u32 = 1;
pub const SETTLED: u32 = 2;
pub const REJECTED: u32 = 3;
pub const CANCELLED: u32 = 4;

/// Buyer information stored in registry
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct BuyerInfo {
    pub name: String,
    pub lei_id: String,
    pub wallet_address: Address,
    pub registered_at: u64,
    pub is_active: bool,
}

/// Seller information stored in registry
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SellerInfo {
    pub name: String,
    pub lei_id: String,
    pub wallet_address: Address,
    pub registered_at: u64,
    pub is_active: bool,
}

/// Core trade escrow record
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TradeEscrow {
    pub trade_id: u64,
    pub buyer: Address,
    pub seller: Address,
    pub amount: i128,
    pub state: u32,
    pub created_at: u64,
    pub fulfilled_at: u64,
    pub settled_at: u64,
    pub marketplace_fee: i128,
    pub escrow_balance: i128,
}

/// Purchase Order created by buyer
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PurchaseOrder {
    pub po_description: String,
    pub quantity: u64,
    pub unit_price: i128,
    pub total_price: i128,
    pub po_json_ipfs_hash: String,
    pub created_by: Address,
    pub created_at: u64,
}

/// Customer Invoice generated by seller
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CustomerInvoice {
    pub ci_description: String,
    pub quantity: u64,
    pub unit_price: i128,
    pub total_price: i128,
    pub ci_json_ipfs_hash: String,
    pub created_by: Address,
    pub created_at: u64,
}

/// Warehouse Receipt generated by seller
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WarehouseReceipt {
    pub wr_description: String,
    pub quantity: u64,
    pub unit_price: i128,
    pub total_price: i128,
    pub wr_json_ipfs_hash: String,
    pub warehouse_location: String,
    pub created_by: Address,
    pub created_at: u64,
}

/// vLEI documents for GLEIF validation
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct VLEIDocuments {
    pub buyer_lei: String,
    pub buyer_lei_ipfs: String,
    pub buyer_validated: bool,
    pub seller_lei: String,
    pub seller_lei_ipfs: String,
    pub seller_validated: bool,
    pub validation_timestamp: u64,
}
